### PR TITLE
Add launch configuration for cameras

### LINKED ISSUE #17: [Feature Request] Remove automatic launch of L3XZ cameras from this ROS node.
<a href="https://107-systems.org/"></a>

### ⚡ Feature Request

Instead of starting the L3XZ OpenMV cameras within this node the launch shall happen within the [robot-local launch](https://github.com/107-systems/l3xz/blob/main/launch/robot.py) file.

### PR DESCRIPTION
**Pull request by wuehr1999**
Fixes #17 
Hi  @aentinger I added the launch configuration for the cameras, but I don't know the right tty paths.

### CODE REVIEW

**Review by aentinger — CHANGES_REQUESTED** [review]
Hi @wuehr1999 :coffee: :wave:
* colour camera: `/dev/serial/by-id/usb-OpenMV_OpenMV_Virtual_Comm_Port_in_FS_Mode_387C357D3330-if00`
* thermal camera: `/dev/serial/by-id/usb-OpenMV_OpenMV_Virtual_Comm_Port_in_FS_Mode_3172326E3330-if00`

Please update the launch file accordingly.

**Comment by wuehr1999** [comment]
Done :+1:

**Comment by aentinger** [comment]
Does it also make sense to automatically start the required static transform publishers?

**Comment by wuehr1999** [comment]
I would have it in the launch example. It is handy when the code is already there, if You need it.

**Comment by wuehr1999** [comment]
I would not make static transform publishers, as the cameras can be moved on the sensor head.

**Review by aentinger — APPROVED** [review]
LGTM :+1: Thank you @wuehr1999 :rocket:

**Pull request merged**
